import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Root from './Root'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Triumph',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Root>
          <Navbar />
          {children}
        </Root>
      </body>
    </html>
  )
}
