import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Root from './Root'
import GlobalLoader from '@/components/ui/GlobalLoader'
import Alert from '@/components/ui/Alert'
const inter = Inter({ subsets: ['latin'] })
import NextTopLoader from 'nextjs-toploader';
import LoadingBar from 'react-top-loading-bar'

export const metadata: Metadata = {
  title: 'Triumph',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color='#000' />
        <Root>

          <GlobalLoader />
          <Alert />
          <Navbar />
          {children}
        </Root>
      </body>
    </html>
  )
}
